// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.11
// source: good.proto

package good

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_Default Status = 0 // 未上架
	Status_Listing Status = 1 // 上架
	Status_DElIST  Status = 2 // 下架
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "Default",
		1: "Listing",
		2: "DElIST",
	}
	Status_value = map[string]int32{
		"Default": 0,
		"Listing": 1,
		"DElIST":  2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_good_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_good_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{0}
}

type GoodsInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GoodsName string `protobuf:"bytes,2,opt,name=goodsName,proto3" json:"goodsName,omitempty"`
	Status    Status `protobuf:"varint,3,opt,name=status,proto3,enum=good.Status" json:"status,omitempty"`
	Image     string `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	UserID    int64  `protobuf:"varint,5,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *GoodsInfo) Reset() {
	*x = GoodsInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_good_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfo) ProtoMessage() {}

func (x *GoodsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfo.ProtoReflect.Descriptor instead.
func (*GoodsInfo) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{0}
}

func (x *GoodsInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GoodsInfo) GetGoodsName() string {
	if x != nil {
		return x.GoodsName
	}
	return ""
}

func (x *GoodsInfo) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_Default
}

func (x *GoodsInfo) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *GoodsInfo) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type CreateGoodsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *GoodsInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *CreateGoodsRequest) Reset() {
	*x = CreateGoodsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_good_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGoodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGoodsRequest) ProtoMessage() {}

func (x *CreateGoodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGoodsRequest.ProtoReflect.Descriptor instead.
func (*CreateGoodsRequest) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGoodsRequest) GetInfo() *GoodsInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type CreateGoodsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *GoodsInfo `protobuf:"bytes,1,opt,name=Info,proto3" json:"Info,omitempty"`
}

func (x *CreateGoodsResponse) Reset() {
	*x = CreateGoodsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_good_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGoodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGoodsResponse) ProtoMessage() {}

func (x *CreateGoodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGoodsResponse.ProtoReflect.Descriptor instead.
func (*CreateGoodsResponse) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{2}
}

func (x *CreateGoodsResponse) GetInfo() *GoodsInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// 商品规格
type GoodsSpecification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID                int64            `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	GoodsId           int64            `protobuf:"varint,2,opt,name=GoodsId,proto3" json:"GoodsId,omitempty"`
	SpecificationName string           `protobuf:"bytes,3,opt,name=specificationName,proto3" json:"specificationName,omitempty"`
	AttributeList     []*AttributeList `protobuf:"bytes,4,rep,name=attributeList,proto3" json:"attributeList,omitempty"`
}

func (x *GoodsSpecification) Reset() {
	*x = GoodsSpecification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_good_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsSpecification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsSpecification) ProtoMessage() {}

func (x *GoodsSpecification) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsSpecification.ProtoReflect.Descriptor instead.
func (*GoodsSpecification) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{3}
}

func (x *GoodsSpecification) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *GoodsSpecification) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *GoodsSpecification) GetSpecificationName() string {
	if x != nil {
		return x.SpecificationName
	}
	return ""
}

func (x *GoodsSpecification) GetAttributeList() []*AttributeList {
	if x != nil {
		return x.AttributeList
	}
	return nil
}

// 商品规格属性
type AttributeList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SpecificationID int64  `protobuf:"varint,2,opt,name=SpecificationID,proto3" json:"SpecificationID,omitempty"`
	Value           string `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
	Sku             *Sku   `protobuf:"bytes,4,opt,name=sku,proto3" json:"sku,omitempty"`
}

func (x *AttributeList) Reset() {
	*x = AttributeList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_good_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttributeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeList) ProtoMessage() {}

func (x *AttributeList) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeList.ProtoReflect.Descriptor instead.
func (*AttributeList) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{4}
}

func (x *AttributeList) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AttributeList) GetSpecificationID() int64 {
	if x != nil {
		return x.SpecificationID
	}
	return 0
}

func (x *AttributeList) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *AttributeList) GetSku() *Sku {
	if x != nil {
		return x.Sku
	}
	return nil
}

type Sku struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AttributeListId int64  `protobuf:"varint,2,opt,name=AttributeListId,proto3" json:"AttributeListId,omitempty"`
	GoodsPrice      string `protobuf:"bytes,3,opt,name=GoodsPrice,proto3" json:"GoodsPrice,omitempty"`
	Stock           int64  `protobuf:"varint,4,opt,name=Stock,proto3" json:"Stock,omitempty"`
}

func (x *Sku) Reset() {
	*x = Sku{}
	if protoimpl.UnsafeEnabled {
		mi := &file_good_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sku) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sku) ProtoMessage() {}

func (x *Sku) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sku.ProtoReflect.Descriptor instead.
func (*Sku) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{5}
}

func (x *Sku) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Sku) GetAttributeListId() int64 {
	if x != nil {
		return x.AttributeListId
	}
	return 0
}

func (x *Sku) GetGoodsPrice() string {
	if x != nil {
		return x.GoodsPrice
	}
	return ""
}

func (x *Sku) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

// 添加商品规格属性
type CreateSpecificationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsId           int64            `protobuf:"varint,1,opt,name=GoodsId,proto3" json:"GoodsId,omitempty"`
	SpecificationName string           `protobuf:"bytes,2,opt,name=specificationName,proto3" json:"specificationName,omitempty"`
	AttributeList     []*AttributeList `protobuf:"bytes,3,rep,name=attributeList,proto3" json:"attributeList,omitempty"`
}

func (x *CreateSpecificationRequest) Reset() {
	*x = CreateSpecificationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_good_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSpecificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSpecificationRequest) ProtoMessage() {}

func (x *CreateSpecificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSpecificationRequest.ProtoReflect.Descriptor instead.
func (*CreateSpecificationRequest) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{6}
}

func (x *CreateSpecificationRequest) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *CreateSpecificationRequest) GetSpecificationName() string {
	if x != nil {
		return x.SpecificationName
	}
	return ""
}

func (x *CreateSpecificationRequest) GetAttributeList() []*AttributeList {
	if x != nil {
		return x.AttributeList
	}
	return nil
}

type CreateSpecificationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsSpecification *GoodsSpecification `protobuf:"bytes,1,opt,name=goodsSpecification,proto3" json:"goodsSpecification,omitempty"`
	AttributeList      []*AttributeList    `protobuf:"bytes,2,rep,name=attributeList,proto3" json:"attributeList,omitempty"`
}

func (x *CreateSpecificationResponse) Reset() {
	*x = CreateSpecificationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_good_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSpecificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSpecificationResponse) ProtoMessage() {}

func (x *CreateSpecificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSpecificationResponse.ProtoReflect.Descriptor instead.
func (*CreateSpecificationResponse) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{7}
}

func (x *CreateSpecificationResponse) GetGoodsSpecification() *GoodsSpecification {
	if x != nil {
		return x.GoodsSpecification
	}
	return nil
}

func (x *CreateSpecificationResponse) GetAttributeList() []*AttributeList {
	if x != nil {
		return x.AttributeList
	}
	return nil
}

type CreateGoodsInfosRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsSpecification *GoodsSpecification `protobuf:"bytes,2,opt,name=GoodsSpecification,proto3" json:"GoodsSpecification,omitempty"` //商品规格属性值和sku
}

func (x *CreateGoodsInfosRequest) Reset() {
	*x = CreateGoodsInfosRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_good_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGoodsInfosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGoodsInfosRequest) ProtoMessage() {}

func (x *CreateGoodsInfosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGoodsInfosRequest.ProtoReflect.Descriptor instead.
func (*CreateGoodsInfosRequest) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{8}
}

func (x *CreateGoodsInfosRequest) GetGoodsSpecification() *GoodsSpecification {
	if x != nil {
		return x.GoodsSpecification
	}
	return nil
}

type CreateGoodsInfosResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsInfo          *GoodsInfo          `protobuf:"bytes,1,opt,name=GoodsInfo,proto3" json:"GoodsInfo,omitempty"`                   // 商品信息
	GoodsSpecification *GoodsSpecification `protobuf:"bytes,2,opt,name=GoodsSpecification,proto3" json:"GoodsSpecification,omitempty"` //商品规格属性值和sku
}

func (x *CreateGoodsInfosResponse) Reset() {
	*x = CreateGoodsInfosResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_good_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGoodsInfosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGoodsInfosResponse) ProtoMessage() {}

func (x *CreateGoodsInfosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGoodsInfosResponse.ProtoReflect.Descriptor instead.
func (*CreateGoodsInfosResponse) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{9}
}

func (x *CreateGoodsInfosResponse) GetGoodsInfo() *GoodsInfo {
	if x != nil {
		return x.GoodsInfo
	}
	return nil
}

func (x *CreateGoodsInfosResponse) GetGoodsSpecification() *GoodsSpecification {
	if x != nil {
		return x.GoodsSpecification
	}
	return nil
}

// 商品规格
type GoodsSpecification2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID                int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	GoodsId           int64  `protobuf:"varint,2,opt,name=GoodsId,proto3" json:"GoodsId,omitempty"`
	SpecificationName string `protobuf:"bytes,3,opt,name=specificationName,proto3" json:"specificationName,omitempty"`
}

func (x *GoodsSpecification2) Reset() {
	*x = GoodsSpecification2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_good_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsSpecification2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsSpecification2) ProtoMessage() {}

func (x *GoodsSpecification2) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsSpecification2.ProtoReflect.Descriptor instead.
func (*GoodsSpecification2) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{10}
}

func (x *GoodsSpecification2) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *GoodsSpecification2) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *GoodsSpecification2) GetSpecificationName() string {
	if x != nil {
		return x.SpecificationName
	}
	return ""
}

// 商品规格属性
type AttributeList2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SpecificationID int64  `protobuf:"varint,2,opt,name=SpecificationID,proto3" json:"SpecificationID,omitempty"`
	Value           string `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *AttributeList2) Reset() {
	*x = AttributeList2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_good_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttributeList2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeList2) ProtoMessage() {}

func (x *AttributeList2) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeList2.ProtoReflect.Descriptor instead.
func (*AttributeList2) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{11}
}

func (x *AttributeList2) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AttributeList2) GetSpecificationID() int64 {
	if x != nil {
		return x.SpecificationID
	}
	return 0
}

func (x *AttributeList2) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetGoodsInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsId int64 `protobuf:"varint,1,opt,name=GoodsId,proto3" json:"GoodsId,omitempty"`
}

func (x *GetGoodsInfoRequest) Reset() {
	*x = GetGoodsInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_good_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGoodsInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodsInfoRequest) ProtoMessage() {}

func (x *GetGoodsInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodsInfoRequest.ProtoReflect.Descriptor instead.
func (*GetGoodsInfoRequest) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{12}
}

func (x *GetGoodsInfoRequest) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

type GetGoodsInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsInfo          *GoodsInfo             `protobuf:"bytes,1,opt,name=GoodsInfo,proto3" json:"GoodsInfo,omitempty"`
	GoodsSpecification []*GoodsSpecification2 `protobuf:"bytes,2,rep,name=GoodsSpecification,proto3" json:"GoodsSpecification,omitempty"`
	AttributeList      []*AttributeList2      `protobuf:"bytes,3,rep,name=AttributeList,proto3" json:"AttributeList,omitempty"`
	Sku                []*Sku                 `protobuf:"bytes,4,rep,name=sku,proto3" json:"sku,omitempty"`
}

func (x *GetGoodsInfoResponse) Reset() {
	*x = GetGoodsInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_good_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGoodsInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodsInfoResponse) ProtoMessage() {}

func (x *GetGoodsInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_good_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodsInfoResponse.ProtoReflect.Descriptor instead.
func (*GetGoodsInfoResponse) Descriptor() ([]byte, []int) {
	return file_good_proto_rawDescGZIP(), []int{13}
}

func (x *GetGoodsInfoResponse) GetGoodsInfo() *GoodsInfo {
	if x != nil {
		return x.GoodsInfo
	}
	return nil
}

func (x *GetGoodsInfoResponse) GetGoodsSpecification() []*GoodsSpecification2 {
	if x != nil {
		return x.GoodsSpecification
	}
	return nil
}

func (x *GetGoodsInfoResponse) GetAttributeList() []*AttributeList2 {
	if x != nil {
		return x.AttributeList
	}
	return nil
}

func (x *GetGoodsInfoResponse) GetSku() []*Sku {
	if x != nil {
		return x.Sku
	}
	return nil
}

var File_good_proto protoreflect.FileDescriptor

var file_good_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x67, 0x6f, 0x6f, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x6f,
	0x6f, 0x64, 0x22, 0x8d, 0x01, 0x0a, 0x09, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x24,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c,
	0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x22, 0x39, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x6f, 0x6f, 0x64,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x2e, 0x47, 0x6f,
	0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x3a, 0x0a,
	0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0xa7, 0x01, 0x0a, 0x12, 0x47, 0x6f,
	0x6f, 0x64, 0x73, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44,
	0x12, 0x18, 0x0a, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x11, 0x73, 0x70,
	0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x39, 0x0a, 0x0d, 0x61, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x0d, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x22, 0x7c, 0x0a, 0x0d, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x53,
	0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x14,
	0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x1b, 0x0a, 0x03, 0x73, 0x6b, 0x75, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x09, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x2e, 0x53, 0x6b, 0x75, 0x52, 0x03, 0x73, 0x6b,
	0x75, 0x22, 0x75, 0x0a, 0x03, 0x53, 0x6b, 0x75, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x41, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0f, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x22, 0x9f, 0x01, 0x0a, 0x1a, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49,
	0x64, 0x12, 0x2c, 0x0a, 0x11, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x73, 0x70,
	0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x39, 0x0a, 0x0d, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x2e, 0x41, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x0d, 0x61, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0xa2, 0x01, 0x0a, 0x1b, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x12, 0x67, 0x6f,
	0x6f, 0x64, 0x73, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x2e, 0x47, 0x6f,
	0x6f, 0x64, 0x73, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x12, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x39, 0x0a, 0x0d, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x6f,
	0x6f, 0x64, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x0d, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22,
	0x63, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e,
	0x66, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x48, 0x0a, 0x12, 0x47, 0x6f,
	0x6f, 0x64, 0x73, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x2e, 0x47, 0x6f,
	0x6f, 0x64, 0x73, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x12, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x93, 0x01, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2d, 0x0a, 0x09, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x2e, 0x47, 0x6f, 0x6f, 0x64,
	0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x48, 0x0a, 0x12, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67,
	0x6f, 0x6f, 0x64, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x12, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x70, 0x65,
	0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x6d, 0x0a, 0x13, 0x47, 0x6f,
	0x6f, 0x64, 0x73, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x32, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49,
	0x44, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x11, 0x73,
	0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x60, 0x0a, 0x0e, 0x41, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x32, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x53,
	0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2f, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x22, 0xe9, 0x01, 0x0a,
	0x14, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x09, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e,
	0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x2e,
	0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x47, 0x6f, 0x6f, 0x64, 0x73,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x49, 0x0a, 0x12, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x70, 0x65,
	0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x70, 0x65,
	0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x52, 0x12, 0x47, 0x6f, 0x6f,
	0x64, 0x73, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x3a, 0x0a, 0x0d, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x2e, 0x41, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x32, 0x52, 0x0d, 0x41, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x03, 0x73,
	0x6b, 0x75, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x2e,
	0x53, 0x6b, 0x75, 0x52, 0x03, 0x73, 0x6b, 0x75, 0x2a, 0x2e, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06,
	0x44, 0x45, 0x6c, 0x49, 0x53, 0x54, 0x10, 0x02, 0x32, 0xe5, 0x01, 0x0a, 0x05, 0x47, 0x6f, 0x6f,
	0x64, 0x73, 0x12, 0x42, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x6f, 0x6f, 0x64,
	0x73, 0x12, 0x18, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x67, 0x6f,
	0x6f, 0x64, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f,
	0x64, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66,
	0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x64,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x0c, 0x47, 0x65, 0x74,
	0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x64,
	0x2e, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x67, 0x6f, 0x6f, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_good_proto_rawDescOnce sync.Once
	file_good_proto_rawDescData = file_good_proto_rawDesc
)

func file_good_proto_rawDescGZIP() []byte {
	file_good_proto_rawDescOnce.Do(func() {
		file_good_proto_rawDescData = protoimpl.X.CompressGZIP(file_good_proto_rawDescData)
	})
	return file_good_proto_rawDescData
}

var file_good_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_good_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_good_proto_goTypes = []interface{}{
	(Status)(0),                         // 0: good.Status
	(*GoodsInfo)(nil),                   // 1: good.GoodsInfo
	(*CreateGoodsRequest)(nil),          // 2: good.CreateGoodsRequest
	(*CreateGoodsResponse)(nil),         // 3: good.CreateGoodsResponse
	(*GoodsSpecification)(nil),          // 4: good.GoodsSpecification
	(*AttributeList)(nil),               // 5: good.AttributeList
	(*Sku)(nil),                         // 6: good.Sku
	(*CreateSpecificationRequest)(nil),  // 7: good.CreateSpecificationRequest
	(*CreateSpecificationResponse)(nil), // 8: good.CreateSpecificationResponse
	(*CreateGoodsInfosRequest)(nil),     // 9: good.CreateGoodsInfosRequest
	(*CreateGoodsInfosResponse)(nil),    // 10: good.CreateGoodsInfosResponse
	(*GoodsSpecification2)(nil),         // 11: good.GoodsSpecification2
	(*AttributeList2)(nil),              // 12: good.AttributeList2
	(*GetGoodsInfoRequest)(nil),         // 13: good.GetGoodsInfoRequest
	(*GetGoodsInfoResponse)(nil),        // 14: good.GetGoodsInfoResponse
}
var file_good_proto_depIdxs = []int32{
	0,  // 0: good.GoodsInfo.status:type_name -> good.Status
	1,  // 1: good.CreateGoodsRequest.info:type_name -> good.GoodsInfo
	1,  // 2: good.CreateGoodsResponse.Info:type_name -> good.GoodsInfo
	5,  // 3: good.GoodsSpecification.attributeList:type_name -> good.AttributeList
	6,  // 4: good.AttributeList.sku:type_name -> good.Sku
	5,  // 5: good.CreateSpecificationRequest.attributeList:type_name -> good.AttributeList
	4,  // 6: good.CreateSpecificationResponse.goodsSpecification:type_name -> good.GoodsSpecification
	5,  // 7: good.CreateSpecificationResponse.attributeList:type_name -> good.AttributeList
	4,  // 8: good.CreateGoodsInfosRequest.GoodsSpecification:type_name -> good.GoodsSpecification
	1,  // 9: good.CreateGoodsInfosResponse.GoodsInfo:type_name -> good.GoodsInfo
	4,  // 10: good.CreateGoodsInfosResponse.GoodsSpecification:type_name -> good.GoodsSpecification
	1,  // 11: good.GetGoodsInfoResponse.GoodsInfo:type_name -> good.GoodsInfo
	11, // 12: good.GetGoodsInfoResponse.GoodsSpecification:type_name -> good.GoodsSpecification2
	12, // 13: good.GetGoodsInfoResponse.AttributeList:type_name -> good.AttributeList2
	6,  // 14: good.GetGoodsInfoResponse.sku:type_name -> good.Sku
	2,  // 15: good.Goods.CreateGoods:input_type -> good.CreateGoodsRequest
	9,  // 16: good.Goods.CreateGoodsInfos:input_type -> good.CreateGoodsInfosRequest
	13, // 17: good.Goods.GetGoodsInfo:input_type -> good.GetGoodsInfoRequest
	3,  // 18: good.Goods.CreateGoods:output_type -> good.CreateGoodsResponse
	10, // 19: good.Goods.CreateGoodsInfos:output_type -> good.CreateGoodsInfosResponse
	14, // 20: good.Goods.GetGoodsInfo:output_type -> good.GetGoodsInfoResponse
	18, // [18:21] is the sub-list for method output_type
	15, // [15:18] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_good_proto_init() }
func file_good_proto_init() {
	if File_good_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_good_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_good_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGoodsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_good_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGoodsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_good_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsSpecification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_good_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttributeList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_good_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sku); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_good_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSpecificationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_good_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSpecificationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_good_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGoodsInfosRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_good_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGoodsInfosResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_good_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsSpecification2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_good_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttributeList2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_good_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGoodsInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_good_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGoodsInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_good_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_good_proto_goTypes,
		DependencyIndexes: file_good_proto_depIdxs,
		EnumInfos:         file_good_proto_enumTypes,
		MessageInfos:      file_good_proto_msgTypes,
	}.Build()
	File_good_proto = out.File
	file_good_proto_rawDesc = nil
	file_good_proto_goTypes = nil
	file_good_proto_depIdxs = nil
}
